### ISSUE TITLE
panic: runtime error: index out of range

### ISSUE THREAD

**Issue by barryzzz** [barryzzz/gadb#5]
panic: runtime error: index out of range

goroutine 1 [running]:
gadb/src/github.com/lsl/gadb.readDevices(0x11c66f0, 0x11c66e0, 0x11c66e0)
	/gadb/src/github.com/lsl/gadb/gadb.go:87 +0x73a
gadb/src/github.com/lsl/gadb.Gadb()
	/gadb/src/github.com/lsl/gadb/gadb.go:112 +0x34
main.main()
	gadb/main.go:6 +0x20

**Comment by barryzzz** [comment]
在设备离线状态下会出现上述问题
